name: ${project.name}
version: ${project.version}
api-version: ${pl.apiver}
description: ${project.description}
main: ${main.class}

author: ${pl.author}
authors: ${pl.authors}

softdepend:
  - PlaceholderAPI

commands:
  omegavision:
    description: The core command for the plugin
    aliases: [ov, ovision, omegav]
  nightvision:
    description: The command to control player night vision
    aliases: [nv, nvision, nightv]
  nightvisionlist:
    description: The command to list all players with night vision
    aliases: [nvlist]
  nightvisionlimit:
    description: The command to control night vision limits
    aliases: [nvlimit]


permissions:
  omegavision.admin:
    description: The wildcard permission to give all the plugin permissions.
    default: false
    children:
      - omegavision.reload
      - omegavision.nightvision.admin
      - omegavision.update
      - omegavision.limit.admin
      - omegavision.blindness.bypass
  omegavision.nightvision.admin:
    description: The wildcard permission to give all the night vision permissions.
    default: false
    children:
      - omegavision.nightvision.toggle
      - omegavision.nightvision.toggle.others
      - omegavision.nightvision.toggle.global
      - omegavision.nightvision.toggle.temp
      - omegavision.nightvision.particles.bypass
      - omegavision.nightvision.world.bypass
      - omegavision.nightvision.list
      - omegavision.nightvision.login
  omegavision.limit.admin:
    description: The wildcard permission to give all the limit permissions.
    default: false
    children:
      - omegavision.limit.check
      - omegavision.limit.check.others
      - omegavision.limit.reset
      - omegavision.limit.bypass
  omegavision.reload:
    description: The permission required to reload the plugin.
    default: false
  omegavision.update:
    description: The permission required to receive plugin update notifications.
    default: false
  omegavision.blindness.bypass:
    description: The permission required to bypass the blindness effect feature.
    default: false
  omegavision.nightvision.toggle:
    description: The permission required to toggle your own night vision on and off.
    default: false
  omegavision.nightvision.toggle.others:
    description: The permission required to toggle night vision for other players.
    default: false
  omegavision.nightvision.toggle.global:
    description: The permission required to toggle night vision for all players currently online.
    default: false
  omegavision.nightvision.toggle.temp:
    description: The permission required to toggle night vision temporarily for a player.
    default: false
  omegavision.nightvision.particles.bypass:
    description: The permission required to bypass the night vision particle effects.
    default: false
  omegavision.nightvision.world.bypass:
    description: The permission required to bypass the disabled worlds for night vision.
    default: false
  omegavision.nightvision.list:
    description: The permission required to list all players who currently have night vision.
    default: false
  omegavision.limit.check:
    description: The permission required to check your own night vision limit status.
    default: false
  omegavision.limit.check.others:
    description: The permission required to check another players night vision limit status.
    default: false
  omegavision.limit.reset:
    description: The permission required to reset a players night vision limit status.
    default: false
  omegavision.limit.bypass:
    description: The permission required to bypass the night vision limit amount
    default: false