name: ${project.name}
version: ${project.version}
api-version: ${pl.apiver}
description: ${project.description}
main: ${main.class}

author: ${pl.author}
authors: ${pl.authors}

commands:
  omegavision:
    description: The main command for omegavision
    aliases: [ov, ovision, omegav]
  nightvision:
    description: The Nightvision toggle command
    aliases: [nv, nvision, nightv]
  nightvisionlist:
    description: The Nightvision List command
    aliases: [nvlist]
  nightvisionlimit:
    description: The NightVision Limit Command
    aliases: [nvlimit]
  nightvisiontemp:
    description: The NightVision Temp Toggle command
    aliases: [nvt, nvtemp]
  nightvisionall:
    description: The NightVision Toggle All command
    aliases: [nva, nvall]

permissions:
  omegavision.admin:
    description: Grants the user access to all commands
    default: false
    children:
      - omegavision.reload
      - omegavision.update
      - omegavision.toggle
      - omegavision.toggle.others
      - omegavision.toggle.all
      - omegavision.toggle.temp
      - omegavision.toggle.global
      - omegavision.bucket
      - omegavision.blindess.bypass
      - omegavision.list
      - omegavision.limit.check
      - omegavision.limit.all
      - omegavision.limit.checkothers
      - omegavision.limit.reset
      - omegavision.limit.bypass
  omegavision.limit.all:
    description: Grants the user access to all the limit commands
    default: false
    children:
      - omegavision.limit.check
      - omegavision.limit.checkothers
      - omegavision.limit.bypass
      - omegavision.limit.reset
  omegavision.toggle.all:
    description: Grants the user access to all the toggle commands
    default: false
    children:
      - omegavision.toggle
      - omegavision.toggle.others
      - omegavision.toggle.global
      - omegavision.toggle.temp
  omegavision.reload:
    description: Grants the user access to the reload command
    default: false
  omegavision.update:
    description: Allows the user to recieve the update messages in-game
    default: false
  omegavision.toggle:
    description: Grants the user access to the toggle command
    default: false
  omegavision.toggle.others:
    description: Grants the user access to the toggle others command
    default: false
  omegavision.toggle.global:
    description: Grants the user access to the toggle all command
    default: false
  omegavision.toggle.temp:
    description: Granst the user access to the toggle temp command
    default: false
  omegavision.bucket:
    description: Allows the user to use buckets to remove the potion effects from nightvision
    default: false
  omegavision.blindness.bypass:
    description: Allows the user to bypass the blindness effect
    default: false
  omegavision.list:
    description: Grants the user access to the nightivison list command
    default: false
  omegavision.limit.check:
    description: Grants the user access to the check limit command
    default: false
  omegavision.limit.checkothers:
    description: Grants the user access to check the limit for other players
    default: false
  omegavision.limit.bypass:
    description: Allows to user to bypass the command limits
    default: false
  omegavision.limit.reset:
    description: Grants the user access to the limit reset command
    default: false